"use client";

import { Suspense, useState, useEffect, useRef, useCallback } from "react";
import { useSearchParams } from "next/navigation";
import dynamic from "next/dynamic";
import Image from "next/image";
import Link from "next/link";
import { Header } from "@/components/header";
import { Search, Play, Loader2, Upload, X, Bell, Settings2, History, ChevronDown } from "lucide-react";
import type { Product } from "@/types/product";
import type { UserPreferences } from "@/types/preferences";
import type { TryOnHistoryGrouped } from "@/types/tryon-history";

const MannequinViewer = dynamic(
  () =>
    import("@/components/mannequin-viewer").then(
      (m) => m.MannequinViewer
    ),
  { ssr: false }
);

interface AnalysisResult {
  product: {
    color: string;
    color_hex: string;
    garment_type: string;
    style: string | null;
    fabric: string | null;
    pattern: string | null;
    fit: string | null;
    details: string | null;
    features: string[] | null;
  } | null;
  person: Record<string, string | number | null> | null;
}

const STORAGE_KEY = "thread_tryon_job";

interface TryOnJob {
  operationName: string;
  product: Product;
  startedAt: number;
}

export default function OutfitPage() {
  return (
    <Suspense>
      <OutfitPageInner />
    </Suspense>
  );
}

function OutfitPageInner() {
  const searchParams = useSearchParams();
  const [prefs, setPrefs] = useState<UserPreferences | null>(null);
  const [products, setProducts] = useState<Product[]>([]);
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [generating, setGenerating] = useState(false);
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [pollMsg, setPollMsg] = useState<string | null>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const mountedRef = useRef(true);
  const [pendingGenerate, setPendingGenerate] = useState(false);
  const hasAutoGenerated = useRef(false);
  const [history, setHistory] = useState<TryOnHistoryGrouped>({});
  const [historyOpen, setHistoryOpen] = useState(false);
  const [historySearch, setHistorySearch] = useState("");
  const historyRef = useRef<HTMLDivElement>(null);
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null);
  const [analyzing, setAnalyzing] = useState(false);
  const lastAnalyzedId = useRef<string | null>(null);

  const TRYON_PRODUCT_KEY = "thread_tryon_product";

  // On mount: check for product in sessionStorage (from "Try it on" button)
  useEffect(() => {
    const shouldGenerate = searchParams.get("generate") === "true";
    const stored = sessionStorage.getItem(TRYON_PRODUCT_KEY);
    if (stored && shouldGenerate && !hasAutoGenerated.current) {
      try {
        const product: Product = JSON.parse(stored);
        sessionStorage.removeItem(TRYON_PRODUCT_KEY);
        hasAutoGenerated.current = true;
        setSelectedProduct(product);
        setPendingGenerate(true);
      } catch {
        sessionStorage.removeItem(TRYON_PRODUCT_KEY);
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Fetch user preferences
  useEffect(() => {
    fetch("/api/preferences")
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (data?.preferences) setPrefs(data.preferences);
        else if (data && !data.preferences) setPrefs(data);
      })
      .catch(() => {});
  }, []);

  // Fetch try-on history
  useEffect(() => {
    fetch("/api/tryon/history")
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (data?.history) setHistory(data.history);
      })
      .catch(() => {});
  }, []);

  // Close history dropdown on click outside
  useEffect(() => {
    if (!historyOpen) return;
    const handler = (e: MouseEvent) => {
      if (historyRef.current && !historyRef.current.contains(e.target as Node)) {
        setHistoryOpen(false);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [historyOpen]);

  // Analyze product when selected (runs once per product)
  useEffect(() => {
    if (!selectedProduct?.image_url || selectedProduct.id === lastAnalyzedId.current) return;
    lastAnalyzedId.current = selectedProduct.id;
    setAnalyzing(true);
    setAnalysis(null);
    fetch("/api/tryon/analyze", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        productImageUrl: selectedProduct.image_url,
        productName: selectedProduct.name,
        productCategory: selectedProduct.category || null,
        personPhotoUrl: prefs?.photo_url || null,
        personInfo: prefs ? {
          gender: prefs.gender,
          height_cm: prefs.height_cm,
          weight_kg: prefs.weight_kg,
          fit_preference: prefs.fit_preference,
        } : null,
      }),
    })
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => { if (data) setAnalysis(data); })
      .catch(() => {})
      .finally(() => setAnalyzing(false));
  }, [selectedProduct, prefs]);

  // Fetch products for selection
  useEffect(() => {
    const params = new URLSearchParams({ limit: "20" });
    if (searchQuery) params.set("category", searchQuery);
    fetch(`/api/products?${params}`)
      .then((r) => r.json())
      .then((data) => setProducts(data.products ?? []))
      .catch(() => {});
  }, [searchQuery]);

  // Request notification permission on mount
  useEffect(() => {
    if ("Notification" in window && Notification.permission === "default") {
      Notification.requestPermission();
    }
  }, []);

  const sendNotification = useCallback((title: string, body: string) => {
    if ("Notification" in window && Notification.permission === "granted") {
      new Notification(title, { body, icon: "/thread-logo.svg" });
    }
  }, []);

  const startPolling = useCallback(
    (opName: string, product: Product) => {
      if (pollRef.current) clearInterval(pollRef.current);

      setGenerating(true);
      setSelectedProduct(product);
      setPollMsg(
        "Generating video — feel free to browse around, we'll notify you when it's ready!"
      );

      let attempts = 0;
      const maxAttempts = 60;

      pollRef.current = setInterval(async () => {
        attempts++;
        if (attempts > maxAttempts) {
          if (pollRef.current) clearInterval(pollRef.current);
          pollRef.current = null;
          sessionStorage.removeItem(STORAGE_KEY);
          if (mountedRef.current) {
            setError("Generation timed out. Please try again.");
            setGenerating(false);
            setPollMsg(null);
          }
          return;
        }

        try {
          const pollRes = await fetch(
            `/api/tryon/video?op=${encodeURIComponent(opName)}`
          );
          const pollData = await pollRes.json();

          if (pollData.error) {
            if (pollRef.current) clearInterval(pollRef.current);
            pollRef.current = null;
            sessionStorage.removeItem(STORAGE_KEY);
            if (mountedRef.current) {
              setError(pollData.error);
              setGenerating(false);
              setPollMsg(null);
            }
            return;
          }

          if (pollData.done && pollData.videoUrl) {
            if (pollRef.current) clearInterval(pollRef.current);
            pollRef.current = null;
            sessionStorage.removeItem(STORAGE_KEY);
            if (mountedRef.current) {
              setVideoUrl(pollData.videoUrl);
              setGenerating(false);
              setPollMsg(null);
            }
            if (document.hidden) {
              sendNotification(
                "Try-on video ready!",
                `Your ${product.name} video is ready to view.`
              );
            }
            // Save to try-on history (with storage URL for replay)
            const savedVideoUrl = pollData.storageUrl || null;
            fetch("/api/tryon/history", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                product_id: product.id,
                product_name: product.name,
                product_image_url: product.image_url,
                product_category: product.category,
                product_brand: product.brand,
                product_price: product.price,
                video_url: savedVideoUrl,
              }),
            }).catch(() => {});
            // Optimistically update local history
            setHistory((prev) => {
              const cat = product.category || "Other";
              const newRecord = {
                id: crypto.randomUUID(),
                user_id: "",
                product_id: product.id,
                product_name: product.name,
                product_image_url: product.image_url,
                product_category: product.category,
                product_brand: product.brand,
                product_price: product.price,
                video_url: savedVideoUrl,
                created_at: new Date().toISOString(),
              };
              return { ...prev, [cat]: [newRecord, ...(prev[cat] || [])] };
            });
          }
        } catch {
          // Keep polling on transient errors
        }
      }, 5000);
    },
    [sendNotification]
  );

  // Resume polling from sessionStorage on mount
  useEffect(() => {
    mountedRef.current = true;
    const stored = sessionStorage.getItem(STORAGE_KEY);
    if (stored) {
      try {
        const job: TryOnJob = JSON.parse(stored);
        if (Date.now() - job.startedAt < 5 * 60 * 1000) {
          startPolling(job.operationName, job.product);
        } else {
          sessionStorage.removeItem(STORAGE_KEY);
        }
      } catch {
        sessionStorage.removeItem(STORAGE_KEY);
      }
    }
    return () => {
      mountedRef.current = false;
      if (pollRef.current) clearInterval(pollRef.current);
    };
  }, [startPolling]);

  const handleGenerate = useCallback(async (product?: Product) => {
    const p = product ?? selectedProduct;
    if (!p) return;
    setGenerating(true);
    setVideoUrl(null);
    setError(null);
    setPollMsg("Starting generation...");

    try {
      const startRes = await fetch("/api/tryon/video", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          productName: p.name,
          productCategory: p.category || null,
          productAnalysis: analysis?.product ?? null,
          personAnalysis: analysis?.person ?? null,
        }),
      });

      if (!startRes.ok) {
        const data = await startRes.json().catch(() => ({}));
        throw new Error(data.error || "Failed to start generation");
      }

      const { operationName } = await startRes.json();
      if (!operationName) throw new Error("No operation name returned");

      const job: TryOnJob = {
        operationName,
        product: p,
        startedAt: Date.now(),
      };
      sessionStorage.setItem(STORAGE_KEY, JSON.stringify(job));

      startPolling(operationName, p);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Generation failed");
      setGenerating(false);
      setPollMsg(null);
    }
  }, [selectedProduct, startPolling, analysis]);

  // Auto-generate: fires once when product is ready and pendingGenerate is set
  useEffect(() => {
    if (pendingGenerate && selectedProduct && !generating && !videoUrl) {
      setPendingGenerate(false);
      handleGenerate(selectedProduct);
    }
  }, [pendingGenerate, selectedProduct, generating, videoUrl, handleGenerate]);

  const heightCm = prefs?.height_cm ?? 170;
  const weightKg = prefs?.weight_kg ?? 70;
  const gender = prefs?.gender ?? "male";
  const fitPref = prefs?.fit_preference ?? "regular";

  return (
    <main className="min-h-screen bg-background">
      <Header />
      <div className="pt-28" />

      <div className="mx-auto max-w-7xl px-6 md:px-12">
        <div className="flex items-center gap-4">
          <div>
            <h1 className="text-4xl font-bold tracking-tight text-foreground md:text-5xl">
              Try On
            </h1>
            <p className="mt-2 text-lg text-muted-foreground">
              See how pieces look with AI-generated video and your 3D body model.
            </p>
          </div>

          {/* ── History dropdown ── */}
          {Object.keys(history).length > 0 && (
            <div className="relative ml-auto" ref={historyRef}>
              <button
                onClick={() => setHistoryOpen(!historyOpen)}
                className="flex items-center gap-2 rounded-full border border-border bg-secondary px-4 py-2.5 text-sm font-medium text-foreground hover:bg-secondary/80 transition-colors"
              >
                <History size={16} />
                History
                <span className="text-xs text-muted-foreground">
                  ({Object.values(history).flat().length})
                </span>
                <ChevronDown
                  size={14}
                  className={`text-muted-foreground transition-transform ${historyOpen ? "rotate-180" : ""}`}
                />
              </button>

              {historyOpen && (
                <div className="absolute right-0 top-full mt-2 z-50 w-[420px] max-h-[520px] rounded-2xl border border-border bg-background shadow-2xl overflow-hidden animate-in fade-in slide-in-from-top-2 duration-200">
                  {/* Search */}
                  <div className="p-3 border-b border-border">
                    <div className="relative">
                      <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
                      <input
                        type="text"
                        value={historySearch}
                        onChange={(e) => setHistorySearch(e.target.value)}
                        placeholder="Search history..."
                        className="w-full rounded-lg border border-border bg-secondary pl-9 pr-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-foreground/30"
                      />
                    </div>
                  </div>

                  {/* Items grouped by category */}
                  <div className="overflow-y-auto max-h-[440px] p-3 space-y-4">
                    {Object.entries(history)
                      .filter(([category, items]) => {
                        if (!historySearch) return true;
                        const q = historySearch.toLowerCase();
                        return (
                          category.toLowerCase().includes(q) ||
                          items.some(
                            (i) =>
                              i.product_name.toLowerCase().includes(q) ||
                              i.product_brand?.toLowerCase().includes(q)
                          )
                        );
                      })
                      .map(([category, items]) => {
                        const filtered = historySearch
                          ? items.filter(
                              (i) =>
                                i.product_name.toLowerCase().includes(historySearch.toLowerCase()) ||
                                i.product_brand?.toLowerCase().includes(historySearch.toLowerCase()) ||
                                category.toLowerCase().includes(historySearch.toLowerCase())
                            )
                          : items;
                        if (filtered.length === 0) return null;
                        return (
                          <div key={category}>
                            <p className="text-[10px] font-medium uppercase tracking-widest text-muted-foreground mb-2 capitalize">
                              {category}
                            </p>
                            <div className="space-y-1">
                              {filtered.map((item) => (
                                <button
                                  key={item.id}
                                  onClick={() => {
                                    setSelectedProduct({
                                      id: item.product_id,
                                      name: item.product_name,
                                      image_url: item.product_image_url,
                                      category: item.product_category,
                                      brand: item.product_brand,
                                      price: item.product_price,
                                      source: "",
                                      description: null,
                                    });
                                    if (item.video_url) {
                                      setVideoUrl(item.video_url);
                                    } else {
                                      setVideoUrl(null);
                                    }
                                    setError(null);
                                    setHistoryOpen(false);
                                  }}
                                  className="flex w-full items-center gap-3 rounded-xl p-2 hover:bg-secondary transition-colors text-left"
                                >
                                  {item.product_image_url && (
                                    <div className="relative h-14 w-11 shrink-0 rounded-lg overflow-hidden bg-secondary">
                                      <Image
                                        src={item.product_image_url}
                                        alt={item.product_name}
                                        fill
                                        className="object-cover"
                                        sizes="44px"
                                      />
                                    </div>
                                  )}
                                  <div className="min-w-0 flex-1">
                                    <p className="text-sm font-medium text-foreground truncate">
                                      {item.product_name}
                                    </p>
                                    <div className="flex items-center gap-2 mt-0.5">
                                      {item.product_brand && (
                                        <span className="text-xs text-muted-foreground">
                                          {item.product_brand}
                                        </span>
                                      )}
                                      {item.product_price != null && (
                                        <span className="text-xs font-medium text-foreground">
                                          ${item.product_price.toFixed(2)}
                                        </span>
                                      )}
                                    </div>
                                  </div>
                                  {item.video_url && (
                                    <Play size={14} className="shrink-0 text-muted-foreground" />
                                  )}
                                </button>
                              ))}
                            </div>
                          </div>
                        );
                      })}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* ── Bento Grid ── */}
      <div className="mx-auto max-w-[1400px] px-6 py-8 md:px-12">
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-3 lg:grid-rows-[420px_320px_auto]">

          {/* ── Video / Generation — spans 2 cols, 2 rows ── */}
          <div className="relative rounded-2xl bg-secondary overflow-hidden lg:col-span-2 lg:row-span-2 flex items-center justify-center min-h-[500px] lg:min-h-0">
            {videoUrl ? (
              <div className="flex h-full w-full">
                {/* Product card pinned left */}
                {selectedProduct && (
                  <div className="hidden lg:flex flex-col items-center gap-3 p-5 bg-background/80 backdrop-blur-sm border-r border-border w-64 shrink-0 self-stretch">
                    <div className="relative flex-1 w-full rounded-xl overflow-hidden bg-secondary">
                      {selectedProduct.image_url && (
                        <Image
                          src={selectedProduct.image_url}
                          alt={selectedProduct.name}
                          fill
                          className="object-cover"
                          sizes="240px"
                        />
                      )}
                    </div>
                    <div className="text-center shrink-0">
                      <p className="text-xs font-semibold text-foreground line-clamp-2">
                        {selectedProduct.name}
                      </p>
                      {selectedProduct.brand && (
                        <p className="text-[10px] text-muted-foreground mt-0.5">
                          {selectedProduct.brand}
                        </p>
                      )}
                      {selectedProduct.price != null && (
                        <p className="text-sm font-bold text-foreground mt-1">
                          ${selectedProduct.price.toFixed(2)}
                        </p>
                      )}
                    </div>
                  </div>
                )}
                <video
                  ref={videoRef}
                  src={videoUrl}
                  className="h-full flex-1 object-contain"
                  controls
                  autoPlay
                  loop
                />
              </div>
            ) : generating ? (
              <div className="flex h-full w-full items-center">
                {/* Product card pinned left while generating */}
                {selectedProduct && (
                  <div className="hidden lg:flex flex-col items-center gap-3 p-5 border-r border-border w-64 shrink-0 self-stretch">
                    <div className="relative flex-1 w-full rounded-xl overflow-hidden bg-background">
                      {selectedProduct.image_url && (
                        <Image
                          src={selectedProduct.image_url}
                          alt={selectedProduct.name}
                          fill
                          className="object-cover"
                          sizes="240px"
                        />
                      )}
                    </div>
                    <div className="text-center shrink-0">
                      <p className="text-xs font-semibold text-foreground line-clamp-2">
                        {selectedProduct.name}
                      </p>
                      {selectedProduct.brand && (
                        <p className="text-[10px] text-muted-foreground mt-0.5">
                          {selectedProduct.brand}
                        </p>
                      )}
                      {selectedProduct.price != null && (
                        <p className="text-sm font-bold text-foreground mt-1">
                          ${selectedProduct.price.toFixed(2)}
                        </p>
                      )}
                    </div>
                  </div>
                )}
                <div className="flex flex-1 flex-col items-center gap-4 px-8 text-center">
                  <Loader2
                    size={36}
                    className="animate-spin text-muted-foreground"
                  />
                  <p className="text-sm text-muted-foreground max-w-xs">{pollMsg}</p>
                  <div className="flex items-center gap-2 rounded-full bg-foreground/5 border border-border px-4 py-2">
                    <Bell size={14} className="text-muted-foreground" />
                    <p className="text-xs text-muted-foreground">
                      We&apos;ll notify you when it&apos;s done
                    </p>
                  </div>
                </div>
              </div>
            ) : selectedProduct ? (
              <div className="flex flex-col items-center gap-5">
                <div className="relative h-52 w-40 rounded-xl overflow-hidden bg-background shadow-lg">
                  {selectedProduct.image_url && (
                    <Image
                      src={selectedProduct.image_url}
                      alt={selectedProduct.name}
                      fill
                      className="object-cover"
                      sizes="160px"
                    />
                  )}
                </div>
                <div className="text-center">
                  <p className="text-sm font-semibold text-foreground">
                    {selectedProduct.name}
                  </p>
                  {selectedProduct.price != null && (
                    <p className="text-sm text-muted-foreground">
                      ${selectedProduct.price.toFixed(2)}
                    </p>
                  )}
                </div>
                <button
                  onClick={handleGenerate}
                  className="flex items-center gap-2 rounded-full bg-foreground px-7 py-3 text-sm font-semibold text-background hover:opacity-80 transition-opacity"
                >
                  <Play size={16} />
                  Generate Video
                </button>
              </div>
            ) : (
              <div className="flex flex-col items-center gap-3 text-muted-foreground">
                <Upload size={36} />
                <p className="text-sm">Select a product below to try on</p>
              </div>
            )}

            {error && (
              <div className="absolute bottom-4 left-4 right-4 rounded-xl bg-red-500/10 border border-red-500/20 px-4 py-3 text-sm text-red-400">
                {error}
              </div>
            )}

            {videoUrl && (
              <button
                onClick={() => {
                  setVideoUrl(null);
                  setError(null);
                }}
                className="absolute top-3 right-3 rounded-full bg-black/60 p-2 text-white hover:bg-black/80 transition-colors"
              >
                <X size={16} />
              </button>
            )}
          </div>

          {/* ── Mannequin with outfit — top right ── */}
          <div className="relative rounded-2xl bg-secondary overflow-hidden min-h-[400px]">
            <MannequinViewer product={selectedProduct} />

            {/* Settings overlay */}
            <div className="absolute top-3 left-3 flex flex-col gap-1">
              <div className="rounded-lg bg-black/50 backdrop-blur-md px-3 py-2">
                <div className="grid grid-cols-2 gap-x-4 gap-y-0.5 text-[11px] text-white/80">
                  <span className="text-white/40">Height</span>
                  <span className="font-medium">{heightCm} cm</span>
                  <span className="text-white/40">Weight</span>
                  <span className="font-medium">{weightKg} kg</span>
                </div>
              </div>
              <Link
                href="/preferences"
                className="flex items-center gap-1 rounded-full bg-black/50 backdrop-blur-md px-2.5 py-1 text-[10px] text-white/50 hover:text-white transition-colors w-fit"
              >
                <Settings2 size={10} />
                Edit
              </Link>
            </div>

            {!prefs && (
              <div className="absolute inset-0 flex items-center justify-center bg-black/30 backdrop-blur-sm">
                <a
                  href="/preferences"
                  className="rounded-full bg-white px-4 py-2 text-xs font-semibold text-black hover:bg-white/90 transition-colors"
                >
                  Set up preferences
                </a>
              </div>
            )}
          </div>

          {/* ── AI Tags — bottom right ── */}
          <div className="rounded-2xl bg-secondary p-5 flex flex-col justify-between">
            {analyzing ? (
              <div className="flex items-center gap-2 text-muted-foreground">
                <Loader2 size={14} className="animate-spin" />
                <span className="text-xs">Analyzing product...</span>
              </div>
            ) : analysis?.product ? (
              <div>
                <p className="text-[10px] font-medium uppercase tracking-widest text-muted-foreground">
                  AI Analysis
                </p>
                <div className="mt-3 flex flex-wrap gap-1.5">
                  {analysis.product.color && (
                    <span className="inline-flex items-center gap-1.5 rounded-full bg-background border border-border px-2.5 py-1 text-xs text-foreground">
                      <span
                        className="h-2.5 w-2.5 rounded-full shrink-0 border border-border"
                        style={{ backgroundColor: analysis.product.color_hex }}
                      />
                      {analysis.product.color}
                    </span>
                  )}
                  {analysis.product.garment_type && (
                    <span className="rounded-full bg-background border border-border px-2.5 py-1 text-xs text-foreground">
                      {analysis.product.garment_type}
                    </span>
                  )}
                  {analysis.product.fabric && (
                    <span className="rounded-full bg-background border border-border px-2.5 py-1 text-xs text-foreground">
                      {analysis.product.fabric}
                    </span>
                  )}
                  {analysis.product.style && (
                    <span className="rounded-full bg-background border border-border px-2.5 py-1 text-xs text-foreground">
                      {analysis.product.style}
                    </span>
                  )}
                  {analysis.product.fit && (
                    <span className="rounded-full bg-background border border-border px-2.5 py-1 text-xs text-foreground">
                      {analysis.product.fit}
                    </span>
                  )}
                  {analysis.product.pattern && analysis.product.pattern !== "solid" && (
                    <span className="rounded-full bg-background border border-border px-2.5 py-1 text-xs text-foreground">
                      {analysis.product.pattern}
                    </span>
                  )}
                  {analysis.product.details && (
                    <span className="rounded-full bg-background border border-border px-2.5 py-1 text-xs text-muted-foreground">
                      {analysis.product.details}
                    </span>
                  )}
                  {analysis.product.features?.map((f, i) => (
                    <span key={i} className="rounded-full bg-primary/10 border border-primary/20 px-2.5 py-1 text-xs text-primary">
                      {f}
                    </span>
                  ))}
                </div>
              </div>
            ) : (
              <div>
                <p className="text-[10px] font-medium uppercase tracking-widest text-muted-foreground">
                  Body Model
                </p>
                <div className="mt-3 grid grid-cols-2 gap-x-6 gap-y-2">
                  <div>
                    <p className="text-2xl font-bold text-foreground">{heightCm}</p>
                    <p className="text-[11px] text-muted-foreground">cm tall</p>
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-foreground">{weightKg}</p>
                    <p className="text-[11px] text-muted-foreground">kg</p>
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-foreground capitalize">{gender}</p>
                    <p className="text-[11px] text-muted-foreground">gender</p>
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-foreground capitalize">{fitPref}</p>
                    <p className="text-[11px] text-muted-foreground">fit</p>
                  </div>
                </div>
              </div>
            )}
            <Link
              href="/preferences"
              className="mt-4 flex items-center justify-center gap-1.5 rounded-full border border-border py-2 text-xs font-medium text-muted-foreground hover:text-foreground hover:border-foreground/30 transition-colors"
            >
              <Settings2 size={12} />
              Edit preferences
            </Link>
          </div>

          {/* ── Product picker — full width bottom ── */}
          <div className="rounded-2xl border border-border bg-background p-4 lg:col-span-3">
            <div className="relative mb-3">
              <Search
                size={16}
                className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"
              />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Filter by category..."
                className="w-full rounded-full border border-border bg-secondary pl-9 pr-4 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-foreground/30"
              />
            </div>
            <div className="flex gap-3 overflow-x-auto pb-1 scrollbar-hide">
              {products.map((p) => (
                <button
                  key={p.id}
                  onClick={() => {
                    setSelectedProduct(p);
                    setVideoUrl(null);
                    setError(null);
                  }}
                  className={`relative shrink-0 h-28 w-20 rounded-xl overflow-hidden transition-all ${
                    selectedProduct?.id === p.id
                      ? "ring-2 ring-foreground scale-105"
                      : "opacity-70 hover:opacity-100"
                  }`}
                >
                  {p.image_url && (
                    <Image
                      src={p.image_url}
                      alt={p.name}
                      fill
                      className="object-cover"
                      sizes="80px"
                    />
                  )}
                </button>
              ))}
            </div>
          </div>

        </div>
      </div>
    </main>
  );
}
